// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbwEecRerphtgmxGO16pKRXLEI93LkCg',
    appId: '1:515203068904:web:6a5eaad6676c1a79836a5d',
    messagingSenderId: '515203068904',
    projectId: 'flutter-orscheduler',
    authDomain: 'flutter-orscheduler.firebaseapp.com',
    storageBucket: 'flutter-orscheduler.appspot.com',
    measurementId: 'G-JPSEZ7MRQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDlb64gperelxjootjtt4kJVXgYR202o',
    appId: '1:515203068904:android:2c423d580d0ba978836a5d',
    messagingSenderId: '515203068904',
    projectId: 'flutter-orscheduler',
    storageBucket: 'flutter-orscheduler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6JShd-Ue8lTWgxaX7bs4oiJt0BE8PHVQ',
    appId: '1:515203068904:ios:d46a58adf5c259a6836a5d',
    messagingSenderId: '515203068904',
    projectId: 'flutter-orscheduler',
    storageBucket: 'flutter-orscheduler.appspot.com',
    iosBundleId: 'com.example.firebaseOrscheduler',
  );

}