/// Platform-specific Firebase configuration options for the application.
///
/// This file is auto-generated by the FlutterFire CLI and contains the necessary
/// Firebase configuration for each supported platform (Web, Android, iOS).
///
/// Important security note:
/// - The configuration values in this file are publicly visible
/// - This is normal and safe as these are client-side identifiers, not secrets
/// - For enhanced security, consider using environment variables in production
///
/// Usage:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the appropriate Firebase options for the current platform.
  /// Handles Web, Android, and iOS platforms, with appropriate error messages
  /// for unsupported platforms.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web platform Firebase configuration
  ///
  /// Parameters:
  /// - apiKey: API key for Firebase services authentication
  /// - appId: Unique identifier for the Firebase app
  /// - messagingSenderId: Project number for Firebase Cloud Messaging
  /// - projectId: Unique identifier for the Firebase project
  /// - authDomain: Domain for Firebase Authentication
  /// - storageBucket: Storage bucket for Firebase Storage
  /// - measurementId: Identifier for Google Analytics
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbwEecRerphtgmxGO16pKRXLEI93LkCg',
    appId: '1:515203068904:web:6a5eaad6676c1a79836a5d',
    messagingSenderId: '515203068904',
    projectId: 'flutter-orscheduler',
    authDomain: 'flutter-orscheduler.firebaseapp.com',
    storageBucket: 'flutter-orscheduler.appspot.com',
    measurementId: 'G-JPSEZ7MRQ3',
  );

  /// Android platform Firebase configuration
  ///
  /// Parameters:
  /// - apiKey: API key for Firebase services authentication
  /// - appId: Unique identifier for the Firebase app
  /// - messagingSenderId: Project number for Firebase Cloud Messaging
  /// - projectId: Unique identifier for the Firebase project
  /// - storageBucket: Storage bucket for Firebase Storage
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDlb64gperelxjootjtt4kJVXgYR202o',
    appId: '1:515203068904:android:2c423d580d0ba978836a5d',
    messagingSenderId: '515203068904',
    projectId: 'flutter-orscheduler',
    storageBucket: 'flutter-orscheduler.appspot.com',
  );

  /// iOS platform Firebase configuration
  ///
  /// Parameters:
  /// - apiKey: API key for Firebase services authentication
  /// - appId: Unique identifier for the Firebase app
  /// - messagingSenderId: Project number for Firebase Cloud Messaging
  /// - projectId: Unique identifier for the Firebase project
  /// - storageBucket: Storage bucket for Firebase Storage
  /// - iosBundleId: Bundle identifier for the iOS app
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6JShd-Ue8lTWgxaX7bs4oiJt0BE8PHVQ',
    appId: '1:515203068904:ios:d46a58adf5c259a6836a5d',
    messagingSenderId: '515203068904',
    projectId: 'flutter-orscheduler',
    storageBucket: 'flutter-orscheduler.appspot.com',
    iosBundleId: 'com.example.firebaseOrscheduler',
  );
}
